"""empty message

Revision ID: 0c2353010ac8
Revises: acc0581919cf
Create Date: 2021-10-30 15:25:01.414991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c2353010ac8'
down_revision = 'acc0581919cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_attendance', sa.Column('Atime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_attendance', 'Atime')
    # ### end Alembic commands ###
