"""empty message

Revision ID: 116d74f2642a
Revises: 5d4409befce6
Create Date: 2021-10-29 10:59:46.547815

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '116d74f2642a'
down_revision = '5d4409befce6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_situation',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Aid', sa.Integer(), nullable=False),
    sa.Column('Sid', sa.Integer(), nullable=False),
    sa.Column('isSuceess', sa.Boolean(), nullable=False),
    sa.Column('Datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Aid'], ['attendance.Aid'], ),
    sa.ForeignKeyConstraint(['Sid'], ['student.Sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('attendance_ibfk_2', 'attendance', type_='foreignkey')
    op.drop_column('attendance', 'Sid')
    op.drop_column('attendance', 'isSuceess')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance', sa.Column('isSuceess', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('attendance', sa.Column('Sid', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('attendance_ibfk_2', 'attendance', 'student', ['Sid'], ['Sid'])
    op.drop_table('attendance_situation')
    # ### end Alembic commands ###
