"""empty message

Revision ID: 12982b81671b
Revises: 60397352608a
Create Date: 2021-10-29 15:36:43.342381

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '12982b81671b'
down_revision = '60397352608a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_curriculum', sa.Column('Cid', sa.Integer(), nullable=True))
    op.add_column('student_curriculum', sa.Column('Sid', sa.Integer(), nullable=True))
    op.drop_constraint('student_curriculum_ibfk_1', 'student_curriculum', type_='foreignkey')
    op.drop_constraint('student_curriculum_ibfk_2', 'student_curriculum', type_='foreignkey')
    op.create_foreign_key(None, 'student_curriculum', 'curriculum', ['Cid'], ['Cid'])
    op.create_foreign_key(None, 'student_curriculum', 'student', ['Sid'], ['Sid'])
    op.drop_column('student_curriculum', 'student_id')
    op.drop_column('student_curriculum', 'curriculum_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_curriculum', sa.Column('curriculum_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_curriculum', sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_curriculum', type_='foreignkey')
    op.drop_constraint(None, 'student_curriculum', type_='foreignkey')
    op.create_foreign_key('student_curriculum_ibfk_2', 'student_curriculum', 'student', ['student_id'], ['Sid'])
    op.create_foreign_key('student_curriculum_ibfk_1', 'student_curriculum', 'curriculum', ['curriculum_id'], ['Cid'])
    op.drop_column('student_curriculum', 'Sid')
    op.drop_column('student_curriculum', 'Cid')
    # ### end Alembic commands ###
