"""empty message

Revision ID: 4389df51df1c
Revises: aa459809e67c
Create Date: 2021-11-18 15:57:29.759545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4389df51df1c'
down_revision = 'aa459809e67c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('curriculum', sa.Column('Catime', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('curriculum', 'Catime')
    # ### end Alembic commands ###
