"""empty message

Revision ID: 83c399bc133f
Revises: 116d74f2642a
Create Date: 2021-10-29 11:13:10.357523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c399bc133f'
down_revision = '116d74f2642a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('attendance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attendance_id'], ['attendance.Aid'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.Sid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendance')
    # ### end Alembic commands ###
