"""empty message

Revision ID: 83f536af4fba
Revises: 12982b81671b
Create Date: 2021-10-30 11:13:48.948527

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83f536af4fba'
down_revision = '12982b81671b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attendance_situation')
    op.add_column('student_attendance', sa.Column('Aid', sa.Integer(), autoincrement=True, nullable=True))
    op.add_column('student_attendance', sa.Column('Datetime', sa.DateTime(), nullable=True))
    op.add_column('student_attendance', sa.Column('Sid', sa.Integer(), autoincrement=True, nullable=True))
    op.add_column('student_attendance', sa.Column('isSuceess', sa.Boolean(), nullable=False))
    op.drop_constraint('student_attendance_ibfk_2', 'student_attendance', type_='foreignkey')
    op.drop_constraint('student_attendance_ibfk_1', 'student_attendance', type_='foreignkey')
    op.create_foreign_key(None, 'student_attendance', 'attendance', ['Aid'], ['Aid'])
    op.create_foreign_key(None, 'student_attendance', 'student', ['Sid'], ['Sid'])
    op.drop_column('student_attendance', 'student_id')
    op.drop_column('student_attendance', 'attendance_id')
    op.alter_column('student_curriculum', 'Cid',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('student_curriculum', 'Sid',
               existing_type=mysql.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_curriculum', 'Sid',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('student_curriculum', 'Cid',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.add_column('student_attendance', sa.Column('attendance_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('student_attendance', sa.Column('student_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'student_attendance', type_='foreignkey')
    op.drop_constraint(None, 'student_attendance', type_='foreignkey')
    op.create_foreign_key('student_attendance_ibfk_1', 'student_attendance', 'attendance', ['attendance_id'], ['Aid'])
    op.create_foreign_key('student_attendance_ibfk_2', 'student_attendance', 'student', ['student_id'], ['Sid'])
    op.drop_column('student_attendance', 'isSuceess')
    op.drop_column('student_attendance', 'Sid')
    op.drop_column('student_attendance', 'Datetime')
    op.drop_column('student_attendance', 'Aid')
    op.create_table('attendance_situation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Aid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('Sid', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('isSuceess', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('Datetime', mysql.DATETIME(), nullable=True),
    sa.CheckConstraint('(`isSuceess` in (0,1))', name='attendance_situation_chk_1'),
    sa.ForeignKeyConstraint(['Aid'], ['attendance.Aid'], name='attendance_situation_ibfk_1'),
    sa.ForeignKeyConstraint(['Sid'], ['student.Sid'], name='attendance_situation_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
