"""empty message

Revision ID: cee42a3daab1
Revises: 0c2353010ac8
Create Date: 2021-10-30 22:39:09.068344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cee42a3daab1'
down_revision = '0c2353010ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student_attendance', 'Atime')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_attendance', sa.Column('Atime', mysql.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
